name: github pages

on:
  push:
    branches:
      - master # default branch

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: cd package/react-ui && npm install
      - run: cd package/react-ui && npm run docs:build
      - run: echo kotomi.site > ./dist/CNAME
      - name: Docs Deploy 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: package/react-ui/dist